spring.application.name=internhub

spring.datasource.url=jdbc:mysql://localhost:3306/internhub
spring.datasource.username=root
spring.datasource.password=Mysql@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081